### ISSUE TITLE
admin account should not be deletable 

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#18]
<img width="985" alt="screen shot 2017-12-10 at 9 59 31 pm" src="https://user-images.githubusercontent.com/6384236/33817665-816da5fe-ddf5-11e7-90d1-0cb4c7080dc9.png">

**Comment by srinidhinandakumar** [comment]
Yes, there was a small error while retireving user information. I have fixed this and admin accounts will not be available for delete/edit etc.
