### ISSUE TITLE
Option to edit time constraints

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#19]
Users should have the option to edit their inputted time constraints.

**Comment by srinidhinandakumar** [comment]
User can now view all time constraints, delete them and update them.
<img width="1189" alt="screen shot 2017-12-17 at 11 38 56 pm" src="https://user-images.githubusercontent.com/12572165/34094774-84c513a2-e383-11e7-8a60-3bed31a6f5cf.png">
<img width="1163" alt="screen shot 2017-12-17 at 11 39 07 pm" src="https://user-images.githubusercontent.com/12572165/34094775-84dde67a-e383-11e7-93b6-9eb6cb6bfea0.png">
