### ISSUE TITLE
option to edit preferences

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#20]
users should have the option to edit their preferences

**Comment by srinidhinandakumar** [comment]
User can now update interest levels for each added preference
<img width="1221" alt="screen shot 2017-12-18 at 1 34 24 am" src="https://user-images.githubusercontent.com/12572165/34099230-c07e3ca6-e393-11e7-8b45-5f9744623511.png">
<img width="1181" alt="screen shot 2017-12-18 at 1 34 37 am" src="https://user-images.githubusercontent.com/12572165/34099231-c0a2bb1c-e393-11e7-8297-759f7a5114ed.png">
