### ISSUE TITLE
require background to be completed first

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#21]
"Courses" should not be accessible until the background section has been filled and submitted.

**Comment by srinidhinandakumar** [comment]
Done. For all new users who have not added personal details, this message will be displayed.
<img width="1226" alt="screen shot 2017-12-13 at 9 58 22 pm" src="https://user-images.githubusercontent.com/12572165/33977657-c77b861c-e050-11e7-9785-561bba7ae417.png">
