### ISSUE TITLE
order by course name (number)

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#25]
Currently they are sorted by section number
<img width="911" alt="screen shot 2017-12-13 at 4 58 10 pm" src="https://user-images.githubusercontent.com/6384236/33969236-67c1264a-e029-11e7-9ac7-cca07e01309f.png">

**Comment by srinidhinandakumar** [comment]
Done.
<img width="336" alt="screen shot 2017-12-13 at 9 46 48 pm" src="https://user-images.githubusercontent.com/12572165/33977318-2d0904c0-e04f-11e7-9040-2482d79ba40c.png">

**Comment by srinidhinandakumar** [comment]
Ordered by Course Code, Lecture Code and Lab Code
<img width="297" alt="screen shot 2017-12-13 at 9 49 52 pm" src="https://user-images.githubusercontent.com/12572165/33977417-a101a7ce-e04f-11e7-8dab-f7b53456ece5.png">
