### ISSUE TITLE
No need to have name:

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#26]
No need to have "name: Morteza", just the name is fine.

<img width="469" alt="screen shot 2017-12-13 at 4 58 05 pm" src="https://user-images.githubusercontent.com/6384236/33969263-85cdcbb6-e029-11e7-84e1-2cbc1dd275b3.png">

**Comment by srinidhinandakumar** [comment]
Done.
<img width="992" alt="screen shot 2017-12-13 at 9 38 35 pm" src="https://user-images.githubusercontent.com/12572165/33977096-0620a774-e04e-11e7-953f-90bcbf61a63a.png">
