### ISSUE TITLE
Area 'general' missing

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#29]
No option to add 'General' courses. Only BCS, Social,... are available.

**Comment by kaurrajdeep** [comment]
Estimate 0.5

**Comment by kaurrajdeep** [comment]
Is the area 'General' applicable to TA details as well ?
I have added for Course.

Thanks

**Comment by mdehghanim** [comment]
Just for the course is fine.

**Comment by kaurrajdeep** [comment]
Changes pushed. Please let me know if any issues.

**Comment by mdehghanim** [comment]
works
