### ISSUE TITLE
change "Active" to "Status" and put Deactivate/Activate under Action

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#3]
The labels that are currently under "active" should be static. All changes should be made from Action.
<img width="1208" alt="screen shot 2017-12-05 at 11 34 36 am" src="https://user-images.githubusercontent.com/6384236/33626876-af859c60-d9b0-11e7-88e9-cc80e65da015.png">

**Comment by srinidhinandakumar** [comment]
Resolved.
