### ISSUE TITLE
Add constraints for individual days

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#30]
there is no timeslot option for Monday 2-4. There is MW 2-4, but not, for example, for a class that only 
 meets on Mondays 2-6.

**Comment by kaurrajdeep** [comment]
Need to check UI workflow.

**Comment by kaurrajdeep** [comment]
Hi Prof,
  Could you please provide more details ?
  In add Course page, I can see that we can add individual day (Mon through Fri) and add timings.

  Is this for TA where they provide time constraints ?
  Can we provide similar option to manually add time constraint if not from the list of available timings to TA as well?

Regards,
Rajdeep

**Comment by mdehghanim** [comment]
This is for the TA where they have to provide time constraints. I think we should have a list of days, and times from 8am to 8pm. And TAs should be able to put in their time constraints manually.

**Comment by kaurrajdeep** [comment]
Ok. Got it.

**Comment by kaurrajdeep** [comment]
Changes pushed. Please let me know if any issues.

**Comment by mdehghanim** [comment]
done
