### ISSUE TITLE
option to delete previous matching

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#32]
There should be an option where all the previous matchings can be deleted together

**Comment by mdehghanim** [comment]
This option to deactivate already exists. Its under "Run matching". But nothing to automatically delete everything.

**Comment by kaurrajdeep** [comment]
Estimate : 0.5 hr

**Comment by kaurrajdeep** [comment]
Added two options under Run Matching :
- Delete previous Admin Matching
- Delete previous Algorithm Matching

**Comment by kaurrajdeep** [comment]
Changes pushed.

**Comment by mdehghanim** [comment]
I don't see where this option is located

**Comment by kaurrajdeep** [comment]
This is under Matching/Perform Matching.

**Comment by mdehghanim** [comment]
works
