### ISSUE TITLE
when a user is deleted, all its preferences should also be deleted

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#35]

**Comment by kaurrajdeep** [comment]
Estimate : 0.5 hr

**Comment by kaurrajdeep** [comment]
Done : When a User is deleted, delete the entry for it from following tables.
-> User
-> TA
-> TA_Preferences
-> TA_Time_Constraints

**Comment by kaurrajdeep** [comment]
Hi Prof,
 -> I noticed the same issue when the User is deactivated.

To fix it There are two approaches,
1) Add another attribute 'IsActive' to the TA_Preferences, and mark them 1/0 based on action.

2) Delete the preferences, if User is activated in future, User will need to setup preferences again.

Please let me know which of these seems more applicable. 
Same approach will be followed when using the option to delete/deactive all users at once.

Regards,
rajdeep

**Comment by mdehghanim** [comment]
Let's go with option 2.

**Comment by kaurrajdeep** [comment]
Changes pushed.

**Comment by mdehghanim** [comment]
This is fixed
