### ISSUE TITLE
consider overlapping time invervals

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#36]
Overlapping time constraints should be taken in to account. If a user inputs MW 10:00-11:50 as a time constraint, not only classes with MW 10:00-11:50 should be taken off, but classes that meet M 10:00-11:50 and/or W 10:00-11:50  should be off the list as well.

**Comment by kaurrajdeep** [comment]
Hi,
 Solution : While performing algorithm, check for actual time slot duration and not time slot id.
 This will be the fastest solution as UI will remain same.
 Estimate : 3 hr.

Thanks,
rajdeep

**Comment by kaurrajdeep** [comment]
Hi,
 Changes are pushed.

Regards,
Rajdeep

**Comment by kaurrajdeep** [comment]
Please reopen in case of any issue.
