### ISSUE TITLE
Users Not Matched count incorrect

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#37]
This is a small bug. All the users have been matched, but the number of users not matched is shows to be 33.

![screen shot 2018-05-01 at 4 06 16 pm](https://user-images.githubusercontent.com/6384236/39497775-a91c89ca-4d59-11e8-9ae3-982833eb01ef.png)

**Comment by kaurrajdeep** [comment]
Estimate 0.5 hours.

**Comment by kaurrajdeep** [comment]
Corrected bug, also show stats only of Active data.

**Comment by kaurrajdeep** [comment]
Changed pushed.

**Comment by mdehghanim** [comment]
works
