### ISSUE TITLE
SQL script

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#38]
It would be nice to have a script that can generate all the SQL tables automatically.

**Comment by kaurrajdeep** [comment]
Hi,
 Generate as in, create tables or data population?

Regards,
Rajdeep

**Comment by mdehghanim** [comment]
Create tables. So that we can more easily deploy the system on to another server.

**Comment by kaurrajdeep** [comment]
Sql in the commit.
