### ISSUE TITLE
sort based on course code, not ID

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#4]
The IDs are internal to the system. So we should sort based on Course Code.

<img width="1159" alt="screen shot 2017-12-05 at 11 51 03 am" src="https://user-images.githubusercontent.com/6384236/33627538-b076089c-d9b2-11e7-9385-abb95b62cff0.png">

**Comment by srinidhinandakumar** [comment]
Resolved, and replicated for view-sections
