### ISSUE TITLE
When a course is deactivated, its sections should not be displayed

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#5]
165 is currently deactivated, yet the sections associated with it are still on the list.

<img width="1275" alt="screen shot 2017-12-05 at 11 56 41 am" src="https://user-images.githubusercontent.com/6384236/33627798-7445b7ea-d9b3-11e7-926d-a709537eb49f.png">

**Comment by srinidhinandakumar** [comment]
Added an Acitve field to show if that section is active or inactive 
@mdehghanim do you still want me to not display any sections that are inactive?
![screenshot from 2017-12-09 18 59 45](https://user-images.githubusercontent.com/12572165/33801547-371923d0-dd13-11e7-9ea3-9c09bfbfedd9.png)

**Comment by mdehghanim** [comment]
Let's not display them at all.
