### ISSUE TITLE
Only capitalize the fist word in each option

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#9]
one example here, but apply it to all the label
<img width="302" alt="screen shot 2017-12-06 at 8 45 19 pm" src="https://user-images.githubusercontent.com/6384236/33699743-d5285826-dac9-11e7-9bab-a0bc8b024d5e.png">
s

**Comment by srinidhinandakumar** [comment]
Resolved
